# bot_type
OPEN_AI = "openAI"
CHATGPT = "chatGPT"
BAIDU = "baidu"
XUNFEI = "xunfei"
CHATGPTONAZURE = "chatGPTOnAzure"
LINKAI = "linkai"
CLAUDEAI = "claude"
QWEN = "qwen"
GEMINI = "gemini"
OPEN_AI_ASSISTANT = 'OpenAIAssistant'
ARK = 'ark'
GROK = 'grok'

# GPT
GPT35 = "gpt-3.5-turbo"
GPT4 = "gpt-4"
GPT4_TURBO_PREVIEW = "gpt-4-turbo-preview"
GPT4_VISION_PREVIEW = "gpt-4-vision-preview"
GPT4_TURBO = 'gpt-4-turbo'
GPT4_OMNI = 'gpt-4o'
GPT4_OMNI_MINI = 'gpt-4o-mini'
O1_PREVIEW = "o1-preview"
O1_MINI = "o1-mini"
GPT54 = "gpt-5.4"
GPT54_MINI = "gpt-5.4-mini"
GPT54_NANO = "gpt-5.4-nano"

GPT35_LIST = [GPT35]
GPT4_MULTIMODEL_LIST = [GPT4_TURBO, GPT4_OMNI, GPT4_OMNI_MINI]
GPT4_LIST = [GPT4, GPT4_TURBO_PREVIEW, GPT4_VISION_PREVIEW, GPT4_TURBO, GPT4_OMNI, GPT4_OMNI_MINI]
GPT_O1_LIST = [O1_PREVIEW, O1_MINI]
GPT54_LIST = [GPT54, GPT54_MINI, GPT54_NANO]

# GPT_Image
GPT_IMAGE_15 = "gpt-image-1.5"
GPT_IMAGE_2 = "gpt-image-2-plus"
GPT_IMAGE_LIST = [GPT_IMAGE_15, GPT_IMAGE_2]

WHISPER_1 = "whisper-1"
TTS_1 = "tts-1"
TTS_1_HD = "tts-1-hd"

# Claude
CLAUDE_OPUS_47 = "claude-opus-4-7"
CLAUDE_SONNET_46 = "claude-sonnet-4-6"
CLAUDE_OPUS_46 = "claude-opus-4-6"
CLAUDE_HAIKU_45 = "claude-haiku-4-5-20251001"
CLAUDE_35_SONNET = "claude-3-5-sonnet-20240620"
CLAUDE_3_HAIKU = "claude-3-haiku-20240307"
CLAUDE_3_SONNET = "claude-3-sonnet-20240229"
CLAUDE_3_OPUS = "claude-3-opus-20240229"
CLAUDE_21 = "claude-2.1"
CLAUDE_20 = "claude-2.0"
CLAUDE_2_LIST = [CLAUDE_20, CLAUDE_21]
CLAUDE_3_LIST = [CLAUDE_3_HAIKU, CLAUDE_3_SONNET, CLAUDE_3_OPUS]
CLAUDE_35_LIST = [CLAUDE_35_SONNET]
CLAUDE_45_LIST = [CLAUDE_HAIKU_45]
CLAUDE_46_LIST = [CLAUDE_SONNET_46, CLAUDE_OPUS_46]
CLAUDE_47_LIST = [CLAUDE_OPUS_47]
CLAUDE_SDK = CLAUDE_2_LIST + CLAUDE_3_LIST + CLAUDE_35_LIST + CLAUDE_45_LIST + CLAUDE_46_LIST + CLAUDE_47_LIST

# Gooogle_Gemini
GEMINI_1_PRO_LATEST_VERSION = "gemini-1.0-pro-latest"
GEMINI_1_LATEST_STABLE_VERSION = "gemini-1.0-pro"
GEMINI_1_STABLE_VERSION = "gemini-1.0-pro-001"
GEMINI_1_PRO_VISION_LATEST = 'gemini-1.0-pro-vision-latest'
GEMINI_1_PRO_VISION_STABLE = 'gemini-1.0-pro-vision'
GEMINI_15_PRO_LATEST_VERSION = "gemini-1.5-pro-latest"
GEMINI_15_LATEST_STABLE_VERSION = "gemini-1.5-pro"
GEMINI_15_STABLE_VERSION = "gemini-1.5-pro-001"
GEMINI_15_FLASH_LATEST_VERSION = "gemini-1.5-flash-latest"
GEMINI_15_FLASH_LATEST_STABLE_VERSION = "gemini-1.5-flash"
GEMINI_15_FLASH_STABLE_VERSION = "gemini-1.5-flash-001"
GEMINI_2_FLASH_EXP = "gemini-2.0-flash-exp"
GEMINI_2_FLASH_THINK_EXP = "gemini-2.0-flash-think-exp"
GEMINI_2_FLASH = "gemini-2.0-flash"
GEMINI_2_FLASH_LITE = "gemini-2.0-flash-lite"
GEMINI_2_PRO_EXP = "gemini-2.0-pro-exp-02-05"
GEMINI_25_PRO = "gemini-2.5-pro"
GEMINI_25_PRO_PREVRIEW = "gemini-2.5-pro-preview-06-05"
GEMINI_25_FLASH_PREVIEW = "gemini-2.5-flash-preview-05-20"
GEMINI_25_FLASH = "gemini-2.5-flash"
GEMINI_1_PRO_LIST = [GEMINI_1_PRO_LATEST_VERSION, GEMINI_1_LATEST_STABLE_VERSION, GEMINI_1_STABLE_VERSION]
GEMINI_15_PRO_LIST = [GEMINI_15_PRO_LATEST_VERSION, GEMINI_15_LATEST_STABLE_VERSION, GEMINI_15_STABLE_VERSION]
GEMINI_15_FLASH_LIST = [GEMINI_15_FLASH_LATEST_VERSION, GEMINI_15_FLASH_LATEST_STABLE_VERSION, GEMINI_15_FLASH_STABLE_VERSION]
GEMINI_2_FLASH_LIST = [GEMINI_2_FLASH_EXP, GEMINI_2_FLASH_THINK_EXP, GEMINI_2_FLASH, GEMINI_2_PRO_EXP, GEMINI_2_FLASH_LITE]
GEMINI_25_PRO_LIST = [GEMINI_25_PRO_PREVRIEW, GEMINI_25_PRO, GEMINI_25_FLASH_PREVIEW,GEMINI_25_FLASH]
GEMINI_3_FLASH_PREVIEW = "gemini-3-flash-preview"
GEMINI_31_FLASH_LITE_PREVIEW = "gemini-3.1-flash-lite-preview"
GEMINI_31_PRO_PREVIEW = "gemini-3.1-pro-preview"

# Google_Gemini_image
IMAGEN_4 = "imagen-4.0-generate-001"
IMAGEN_4_ULTRA = "imagen-4.0-ultra-generate-001"
IMAGEN_4_FAST = "imagen-4.0-fast-generate-001"
GEMINI_2_FLASH_IMAGE_GENERATION = 'gemini-2.0-flash-preview-image-generation'
GEMINI_25_FLASH_IMAGE = "gemini-2.5-flash-image"
GEMINI_3_PRO_IMAGE_PREVIEW = "gemini-3-pro-image-preview"
GEMINI_31_FLASH_IMAGE_PREVIEW = "gemini-3.1-flash-image-preview"
GOOGLE_IMAGE_LIST = [
    IMAGEN_4, 
    IMAGEN_4_ULTRA, 
    IMAGEN_4_FAST, 
    GEMINI_2_FLASH_IMAGE_GENERATION, 
    GEMINI_25_FLASH_IMAGE, 
    GEMINI_3_PRO_IMAGE_PREVIEW, 
    GEMINI_31_FLASH_IMAGE_PREVIEW
]


# Google_video
VEO_2 = "veo-2.0-generate-001"
VEO_3 = "veo-3.0-generate-001"
VEO_3_FAST = "veo-3.0-fast-generate-001"
VEO_31 = 'veo-3.1-generate-preview'
VEO_31_FAST = 'veo-3.1-fast-generate-preview'
VEO_31_LITE = 'veo-3.1-lite-generate-preview'
VEO_LIST = [VEO_2, VEO_3, VEO_3_FAST, VEO_31, VEO_31_FAST, VEO_31_LITE]

GEMINI_GENAI_SDK = [
    GEMINI_2_FLASH,
    GEMINI_2_FLASH_LITE, 
    GEMINI_2_FLASH_IMAGE_GENERATION, 
    GEMINI_2_PRO_EXP, 
    GEMINI_25_PRO_PREVRIEW, 
    GEMINI_25_PRO, 
    GEMINI_25_FLASH_PREVIEW, 
    GEMINI_25_FLASH, 
    GEMINI_25_FLASH_IMAGE,
    GEMINI_31_PRO_PREVIEW,
    GEMINI_3_FLASH_PREVIEW,
    GEMINI_31_FLASH_LITE_PREVIEW
] + VEO_LIST + GOOGLE_IMAGE_LIST


# Doubao_Seed
DOUBAO_SEED_16 = "doubao-seed-1-6-251015"
DOUBAO_SEED_18 = "doubao-seed-1-8-251228"
DOUBAO_SEED_20 = "doubao-seed-2-0-pro-260215"
DOUBAO_SEED_20_MINI = "doubao-seed-2-0-mini-260215"
DOUBAO_SEED_20_LITE = "doubao-seed-2-0-lite-260215"

DOUOBAO_SEED_LIST = [DOUBAO_SEED_16, DOUBAO_SEED_18, DOUBAO_SEED_20, DOUBAO_SEED_20_MINI, DOUBAO_SEED_20_LITE]

# Doubao_Seedream
DOUBAO_SEEDREAM_4 = "doubao-seedream-4-0-250828"
DOUBAO_SEEDREAM_45 = "doubao-seedream-4-5-251128"
DOUBAO_SEEDREAM_5 = "doubao-seedream-5-0-260128"
DOUBAO_SEEDREAM_LIST = [DOUBAO_SEEDREAM_4, DOUBAO_SEEDREAM_45, DOUBAO_SEEDREAM_5]

# Doubao_Seedance
DOUBAO_SEEDANCE_10_PRO = "doubao-seedance-1-0-pro-250528"
DOUBAO_SEEDANCE_10_PRO_FAST = "doubao-seedance-1-0-pro-fast-251015"
DOUBAO_SEEDANCE_10_LITE_I2V = "doubao-seedance-1-0-lite-i2v-250428"
DOUBAO_SEEDANCE_10_LITE_T2V = "doubao-seedance-1-0-lite-t2v-250428"
DOUBAO_SEEDANCE_15_PRO = "doubao-seedance-1-5-pro-251215"
DOUBAO_SEEDANCE_20 = "doubao-seedance-2-0-260128"
DOUBAO_SEEDANCE_20_FAST = "doubao-seedance-2-0-fast-260128"
DOUBAO_SEEDANCE_LIST = [
    DOUBAO_SEEDANCE_10_PRO, 
    DOUBAO_SEEDANCE_10_PRO_FAST, 
    DOUBAO_SEEDANCE_10_LITE_I2V, 
    DOUBAO_SEEDANCE_10_LITE_T2V,
    DOUBAO_SEEDANCE_15_PRO,
    DOUBAO_SEEDANCE_20,
    DOUBAO_SEEDANCE_20_FAST
]

# Doubao_Bot
DOUBAO_BOT_16 = "bot-20251112121022-hph6d"
DOUBAO_BOT_LIST = [DOUBAO_BOT_16]

DOUAO = DOUOBAO_SEED_LIST + DOUBAO_SEEDREAM_LIST + DOUBAO_SEEDANCE_LIST + DOUBAO_BOT_LIST

# Kling_image
KLING_V1 = "kling-v1"
KLING_V1_5 = "kling-v1-5"
KLING_V2 = "kling-v2"
KLING_V2_NEW = "kling-v2-new"
KLING_V2_1 = "kling-v2-1"
KLING_V3 = "kling-v3"
KLING_IMAGE_O1 = "kling-image-o1"

# Kling_video
KLING_V1 = "kling-v1"
KLING_V1_6 = "kling-v1-6"
KLING_V2_MASTER = "kling-v2-master"
KLING_V2_1_MASTER = "kling-v2-1-master"
KLING_V2_5_TURBO = "kling-v2-5-turbo"
KLING_V2_6 ="kling-v2-6"
KLING_V3 = "kling-v3"

# Kling omni
KLING_VIDEO_O1 = "kling-video-o1"
KLING_V3_OMNI = "kling-v3-omni"

KLING_NORMALIMAGE_LIST = [KLING_V1, KLING_V1_5, KLING_V2, KLING_V2_NEW, KLING_V2_1, KLING_V3]
KLING_OMNI_IMAGE_LIST = [KLING_IMAGE_O1, KLING_V3_OMNI]
KLING_IMAGE_LIST = KLING_NORMALIMAGE_LIST + KLING_OMNI_IMAGE_LIST

KLING_NORMALVIDEO_LIST = [KLING_V1, KLING_V1_6, KLING_V2_MASTER, KLING_V2_1_MASTER, KLING_V2_5_TURBO, KLING_V2_6, KLING_V3]
KLING_OMNI_VIDEO_LIST = [KLING_VIDEO_O1, KLING_V3_OMNI]
KLING_VIDEO_LIST = KLING_NORMALVIDEO_LIST + KLING_OMNI_VIDEO_LIST
KLING_MEDIA_LIST = KLING_IMAGE_LIST + KLING_VIDEO_LIST

# Grok
GROK_42_REASONING = "grok-4.20-0309-reasoning"
GROK_42_NON_REASONING = "grok-4.20-0309-non-reasoning"
GROK_420_MULTI_AGENT = "grok-4.20-multi-agent-0309"
GROK_LIST = [GROK_42_REASONING, GROK_42_NON_REASONING, GROK_420_MULTI_AGENT]

# Grok_image
GROK_IMAGINE_IMAGE = "grok-imagine-image"
GROK_IMAGINE_IMAGE_PRO = "grok-imagine-image-pro"
GROK_IMAGE_LIST = [GROK_IMAGINE_IMAGE, GROK_IMAGINE_IMAGE_PRO]

# Grok_video
GROK_IMAGINE_VIDEO = "grok-imagine-video"
GROK_VIDEO_LIST = [GROK_IMAGINE_VIDEO]

# switch model in cmd
MODEL_LIST = [
    "wenxin",
    "wenxin-4",
    "xunfei",
    QWEN,
    GEMINI,
    OPEN_AI_ASSISTANT,
    GEMINI_1_PRO_LATEST_VERSION,
    GEMINI_15_PRO_LATEST_VERSION,
    GEMINI_15_FLASH_LATEST_VERSION,
    GEMINI_15_FLASH_LATEST_STABLE_VERSION,
    ] + CLAUDE_SDK + GEMINI_GENAI_SDK + DOUAO + KLING_MEDIA_LIST + GROK_LIST + GPT35_LIST + GPT4_LIST + GPT_O1_LIST + GPT54_LIST + GPT_IMAGE_LIST

# channel
FEISHU = "feishu"
DINGTALK = "dingtalk"
TELEGRAM = "telegram"

# media files type
IMAGE = ['png', 'jpg', 'jpeg', 'webp', 'heic', 'heif']
AUDIO = ['wav', 'mp3', 'aiff', 'aac', 'ogg', 'flac']
VIDEO = ['mp4', 'mpeg', 'mov', 'avi', 'x-flv', 'mpg', 'webm', 'wmv', '3gpp']
TXT = ['rtf', 'md', 'css', 'html', 'plain', 'javascript']
DOCUMENT = ['pdf', 'doc', 'docx', 'plain']
SPREADSHEET = ['csv', 'xml']
PRESENTATION = ['ppt', 'pptx']
APPLICATION = ['x-javascript', 'x-python']

# custom service reply
ERROR_RESPONSE = "网络有点小烦忙，请过几秒再试一试，给您带来不便，大超子深表歉意"
